### ISSUE TITLE
Update roadmap document

### ISSUE THREAD

**Issue by cjjcastro** [fga-eps-mds/2019.1-hubcare-docs#73]
**Doc Details**

The current version of the roadmap does not contemplate the delivery dates of each point and only high level requirements exist, although knowing what will be delivered the document does not explain exactly what will be delivered of each thing. Therefore it is necessary to set the dates and low level requirements to increase the granularity of the requirements.

- [ ] Set Delivery Dates
- [ ] Define low level requirements.

Provide details about what needs to be set up, how, and why is it important.

---

**Role**

- [ ] Scrum Master
- [ ] DevOps
- [ ] Architect
- [x] Product Manager

**Prefered Language** (for docs, only)

- [ ] English (for community interest docs)
- [x] Brazilian Portuguese (for stakeholders interest docs)

**Comment by cjjcastro** [comment]
the roadmap cites architecture implementations that will no longer be used in the project. Ex: the use of iframe
